In [1]:
names=['Paul', 'John', 'George', 'Ringo']

print(names)

['Paul', 'John', 'George', 'Ringo']


In [ ]:
numbers=[[1,2,3],[4,5,6],[7,8,9]]
numbers

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
import numpy as np

nums=np.array(numbers)
print(nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
numbers=[[1,2,3],[4,5,6],[7,8,9]]


for row in numbers:
    for num in row:
        print(num, end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


In [8]:
test=[[-1,-2],[[0,1],[1,2]],[4,5,6],[7,8,9]]
print(test)

[[-1, -2], [[0, 1], [1, 2]], [4, 5, 6], [7, 8, 9]]


In [ ]:
marks=[[30,53,63],[29,6,94],[34,2,43]]
marks_np=np.array(marks)
print(marks_np)

[[30, 53, 63], [29, 6, 94], [34, 2, 43]]
[[30 53 63]
 [29  6 94]
 [34  2 43]]


In [14]:
print(marks[1])

print(marks[1][1])

print(marks[2][2])

[29, 6, 94]
6
43


In [16]:
nums=[]

for i in range(100):
    nums.append(i)

print(nums)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [41]:
import random
choices= ['X', 'O']
choice=player1_choice=random.choice(choices)

print(choice)
choices.remove(player1_choice)

print(choices)
player2_choice=random.choice(choices)

print(f'Player 1: {player1_choice} player 2: {player2_choice}')


X
['O']
Player 1: X player 2: O


In [42]:
marks=[[30,53,63],[29,6,94],[34,2,43]]

marks[1][2]=10

print(marks)

[[30, 53, 63], [29, 6, 10], [34, 2, 43]]
